# Generated by Django 4.0.3 on 2022-04-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300, verbose_name='Name:')),
                ('description', models.TextField(max_length=1000, verbose_name='Description:')),
                ('price', models.TextField(max_length=50, verbose_name='Price:')),
                ('city', models.CharField(choices=[('Nur-Sultan', 'Nur-Sultan'), ('Almaty', 'Almaty'), ('Aktobe', 'Aktobe')], max_length=40, verbose_name='City')),
                ('type', models.CharField(choices=[('hotel', 'hotel'), ('park', 'park'), ('museum', 'museum')], max_length=40, verbose_name='Type')),
                ('pic', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=100)),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
