# Generated by Django 4.0.3 on 2022-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='city',
            field=models.CharField(choices=[('Nur-Sultan', 'Nur-Sultan'), ('Almaty', 'Almaty'), ('Aktobe', 'Aktobe'), ('Almaty obl', 'Almaty obl'), ('Atyrau', 'Atyrau')], max_length=40, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='places',
            name='type',
            field=models.CharField(choices=[('hotel', 'hotel'), ('park', 'park'), ('museum', 'museum'), ('shop', 'shop')], max_length=40, verbose_name='Type'),
        ),
    ]
