# Generated by Django 4.0.3 on 2022-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/places', verbose_name='Picture'),
        ),
    ]
