# Generated by Django 4.0.3 on 2022-05-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_places_city_alter_places_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='city',
            field=models.CharField(choices=[('Nur-Sultan', 'Nur-Sultan'), ('Almaty', 'Almaty'), ('Aktobe', 'Aktobe'), ('Almaty obl', 'Almaty obl'), ('Atyrau', 'Atyrau'), ('Kostanay', 'Kostanay')], max_length=40, verbose_name='City'),
        ),
    ]
