# Generated by Django 4.0.3 on 2022-05-21 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_rename_article_comments_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
