# Generated by Django 4.0.3 on 2022-05-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_places_favorites_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='place',
            new_name='places',
        ),
    ]
