# Generated by Django 4.0.3 on 2022-05-21 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_rename_place_bookmark_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='Favorite',
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
