# Generated by Django 4.0.3 on 2022-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_bookmark_favorite_alter_places_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='FirstName',
            field=models.CharField(default='FirstName', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastName',
            field=models.CharField(default='LastName', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='user', max_length=25),
        ),
    ]
