# Generated by Django 4.0.3 on 2022-05-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='firstname', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='lastname', max_length=25),
        ),
    ]
