# Generated by Django 4.0.3 on 2022-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/user.webp', null=True, upload_to='images/avatars', verbose_name='Photo'),
        ),
    ]
