# Generated by Django 4.0.3 on 2022-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='recommend_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='places',
            name='recommend_2',
            field=models.BooleanField(default=False),
        ),
    ]
