# Generated by Django 4.0.3 on 2022-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_places_recommend_1_places_recommend_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
