# Generated by Django 4.0.3 on 2022-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_places_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='city',
            field=models.CharField(choices=[('Nur-Sultan', 'Nur-Sultan'), ('Almaty', 'Almaty'), ('Aktobe', 'Aktobe'), ('Almaty⠀region', 'Almaty⠀region'), ('Atyrau', 'Atyrau'), ('Kostanay', 'Kostanay'), ('Shymkent', 'Shymkent'), ('Akmola region', 'Akmola region'), ('West Kazakhstan region', 'West Kazakhstan region'), ('East Kazakhstan region', 'East Kazakhstan region'), ('Turkestan region', 'Turkestan region'), ('Kostanay', 'Kostanay'), ('Pavlodar', 'Pavlodar'), ('North Kazakhstan region', 'North Kazakhstan region'), ('Mangystau', 'Mangystau'), ('Karaganda', 'Karaganda'), ('Kyzylorda', 'Kyzylorda'), ('Zhambyl region', 'Zhambyl region')], max_length=40, verbose_name='City'),
        ),
    ]
