# Generated by Django 4.0.3 on 2022-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_places_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='pic',
            field=models.ImageField(blank=True, default='images/default_place.png', null=True, upload_to='images/places', verbose_name='Picture'),
        ),
    ]
